import type { NextPage } from "next"
import Popper from "@popperjs/core"
import Link from "next/link"
import Head from "next/head"
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"


// React-Bootstrap icons
import { Spotify } from "react-bootstrap-icons"

// React-Bootstrap imports
import Col from "react-bootstrap/Col"
import Row from "react-bootstrap/Row"
import Card from "react-bootstrap/Card"
import Container from "react-bootstrap/Container"
import Image from "react-bootstrap/Image"
import Accordion from "react-bootstrap/Accordion"

const PollinationForMentees : NextPage = () => {
  
  return (
    <div>
      <Head>
        <title>Beela</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />

        {/* Hero */}
        <div className="container-fluid overflow-hidden" id="wrapper">
        <div className="row p-5" id="jumbotron">
          {/* Hero */}
            <div className="container px-5" id="hero">
                {/* About Beela */}
                <div className="row" id="hero-container">
                    <div className="col py-4 px-5 m-5">
                        <div className="conatiner">
                        <div className="container pb-4 pt-2">
                            <h1 className="no_name_37">Pollination for mentees</h1>
                            <h3 className="no_name_37" >Next cohort starts: Autumn 2022</h3>
                        </div>
                        <div className="container">
                            <h4 >Ready to get into tech? </h4>
                            <p id="about-paragraph">
                            Our free Pollination Mentoring Programme provides a space to grow and blossom.
                            </p>
                            <p className="B1">
                                <ul>
                                    <li>4 month programme</li>
                                    <li>1-on-1 session with a mentor twice a month</li>
                                    <li>Supportive community</li>
                                    <li>3 hours/week time commitment</li>
                                </ul>
                                <Link href="https://docs.google.com/forms/d/1hT1ZjogGSzdND-QvlKj6jqj9ZDbfnQSQE6hWymcXA3I/prefill" ><a target="_blank"><button type="button" className="btn  button slack-btn">Start your application</button></a></Link>
                            </p>
                        </div>
                        </div>
                    </div>
                    <div className="col-5 py-5 px-2 my-5 mx-2">
                        <Image src="/Hero-Image.png" alt="About Beela" width={500} height={340} />
                    </div>
                </div>
            </div>
        </div>

        <Container className="py-5">
            <h2 className="text-center no_name_37 mb-5 py-5">What to expect as a mentee</h2>
            <Row className="mt-4">
                <Col md={6} lg={4} className="text-center">
                    <Card style={{ width: '18rem', position: "relative" }}>
                        <Card.Img variant="top" src="/avatar.png"  className="img-card-relative"/>
                        <Card.Body  className="py-5">
                            <h5>Mentor Matching</h5>
                            <Card.Text>
                                Some quick example text to build on the card title and make up the
                                bulk of the card's content.
                            </Card.Text>
                        </Card.Body>
                    </Card>
                </Col>

                <Col md={6} lg={4} className="text-center">
                    <Card style={{ width: '18rem' }}>
                        <Card.Img variant="top" src="/avatar.png" className="img-card-relative" />
                        <Card.Body  className="py-5">
                        <h5>Networking</h5>
                            <Card.Text>
                                Some quick example text to build on the card title and make up the
                                bulk of the card's content.
                            </Card.Text>
                        </Card.Body>
                    </Card>
                </Col>

                <Col md={6} lg={4} className="text-center">
                    <Card style={{ width: '18rem' }}>
                       
                        <Card.Img variant="top" src="/avatar.png"  className="img-card-relative"/>
                        <Card.Body  className="py-5">
                        <h5>Workshops</h5>
                            <Card.Text>
                                Some quick example text to build on the card title and make up the
                                bulk of the card's content.
                            </Card.Text>
                        </Card.Body>
                    </Card>
                </Col>
          
            </Row>
        </Container>

        <Container className="py-5">
            <h3 className="no_name_37 text-center">Frequently Asked Questions</h3>
            <Accordion defaultActiveKey="0" className="my-5">
            <Accordion.Item eventKey="0">
                    
                        <Accordion.Header className="mb-0">
                            What background do I need to apply for the programme?
                            
                        </Accordion.Header>
                    
                        <Accordion.Body  className="B1">
                            We are open to applicants from a range of backgrounds. Diversity only helps enhance the tech community! We’ve had mentees in our programme who are exploring tech careers, as well as those who are actively applying to jobs.
                        </Accordion.Body>
                    
            </Accordion.Item>

                <Accordion.Item eventKey="1">
                        <Accordion.Header className="mb-0">
                        <span className="mb-0 no_name_37">  What are you looking for in applicants?</span> 
                        </Accordion.Header>
                        <Accordion.Body   className="B1">
                           We are open to applicants from a range of backgrounds. Diversity only helps enhance the tech community! We’ve had mentees in our programme who are exploring tech careers, as well as those who are actively applying to jobs.
                        </Accordion.Body>
                    </Accordion.Item>
              
                

                <Accordion.Item eventKey="2">
                        <Accordion.Header className="mb-0 no_name_37">
                        <span className="mb-0 no_name_37">   What qualifications will my mentor have?</span> 
                        </Accordion.Header>
                        <Accordion.Body   className="B1">
                            We are open to applicants from a range of backgrounds. Diversity only helps enhance the tech community! We’ve had mentees in our programme who are exploring tech careers, as well as those who are actively applying to jobs. 
                        </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="3">
                        <Accordion.Header className="mb-0 no_name_37">
                        <span className="mb-0 no_name_37">  Are the mentor meetings in person or virtual?</span> 
                        </Accordion.Header>
                        <Accordion.Body  className="B1">
                          We are open to applicants from a range of backgrounds. Diversity only helps enhance the tech community! We’ve had mentees in our programme who are exploring tech careers, as well as those who are actively applying to jobs. 
                        </Accordion.Body>
                </Accordion.Item>

                <Accordion.Item eventKey="4">
                        <Accordion.Header className="mb-0 no_name_37">
                       <span className="mb-0 no_name_37">I still have questions. Who should I ask? </span> 
                        </Accordion.Header>
                        <Accordion.Body  className="B1">
                           We are open to applicants from a range of backgrounds. Diversity only helps enhance the tech community! We’ve had mentees in our programme who are exploring tech careers, as well as those who are actively applying to jobs.
                        </Accordion.Body>
                </Accordion.Item>
              
                </Accordion>


        </Container>

       

        
          <Footer />
        </div>
      </main>
    </div>
  )
}

export default PollinationForMentees
