//Next.js component imports
import type { NextPage } from "next"
import Head from "next/head"

//Component imports
import { PriNotice } from "../components/sections/gdpr"

const Privacy: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Beela</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PriNotice />
    </div>
  )
}
export default Privacy
