import type { NextPage } from "next"
import Head from "next/head"

import Hero from "../components/sections/programmes/Hero"
import ApprenticeshipProgramme from "../components/sections/programmes/ApprenticeshipProgramme"
const Programmes: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Beela</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <ApprenticeshipProgramme />
    </div>
  )
}
export default Programmes
