//Next.js component imports
import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import { PageWrapper } from "../components/layout/PageWrapper"

//Components
import Navbar from "../components/layout/Navbar/index"
import StayConnected from "../components/sections/stayconnected/hero/index"
import JoinOurCommunity from "../components/sections/stayconnected/joinourcommunity/join"
import Newsletter from "../components/sections/stayconnected/newsletter/newsletter"
import Podcast from "../components/sections/stayconnected/podcast/podcast"
import Support from "../components/sections/stayconnected/support/support"
import Footer from "../components/layout/Footer/index"

const stayConnected: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Beela</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <PageWrapper>
    <StayConnected />
    <JoinOurCommunity />
    <Newsletter />
    <Podcast />
    <Support />
    <Footer />
    </PageWrapper>
  </div>
  )
}

export default stayConnected