import type { NextPage } from "next"
import Head from "next/head"
import Navbar from "../components/sections/Navbar"
import Footer from "../components/layout/Footer"
import avatar from "../images/avatar.png"
import Image from "next/image"

import Container from "react-bootstrap/Container"
import Row from "react-bootstrap/Row"
import Col from "react-bootstrap/Col"
import Link from "next/link"

const StayConnected: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Beela</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container-fluid" id="wrapper">
        <div className="row p-5" id="jumbotron">
          {/* Hero */}
          <div className="container px-5" id="hero">
            {/* About Beela */}
            <div className="row" id="hero-container">
              <div className="col py-4 px-5 m-5">
                <div className="conatiner">
                  <div className="container pb-4 pt-2">
                    <h1 id="about-beela">Stay Connected</h1>
                  </div>
                  <div className="container">
                    <h4 className="no_name_37">Come join us</h4>
                    <p id="about-paragraph">
                      We&apos;re ready to support your tech journey in Sweden in a variety of ways.
                      We want to welcome you and encourage you along the way. <br />
                      <br /> We can&apos;t wait to connect with you.{" "}
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-5 py-5 px-2 my-5 mx-2">
                <Image src="/images/Hero-Image.png" alt="About Beela" width={500} height={340} />
              </div>
            </div>
          </div>
        </div>

        {/* Our Community */}
        <div className="row" id="community">
          <div className="container">
            <div className="row gx-0 p-5 m-5 align-items-center">
              <div className="col px-5 mx-4">
                <Image src="/images/about-us2 1.png" alt="Our Community" width={520} height={330} />
              </div>
              <div className="col px-5 mx-5">
                <div className="container mb-5">
                  <h1 id="our-community">Join our community</h1>
                </div>
                <div className="container">
                  <h4 className="no_name_37">Our community uses Slack to connect</h4>
                  <p className="B1">
                    If you’ve never used Slack before, it’s okay! It’s a discussion platform that
                    many tech companies use to communicate. We promise you’ll get the hang of it
                    quickly. Here are some of our most popular channels:{" "}
                  </p>
                  <ul>
                    <li>
                      {" "}
                      <b>#welcome</b> Introduce yourself and connect with other immigrants to
                      Sweden.{" "}
                    </li>
                    <li>
                      <b>#encouragement</b> Ask questions, share your experiences, and receive
                      support.
                    </li>
                    <li>
                      <b>#job-leads </b>Share and view job descriptions from employers that welcome
                      diverse applicants.
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Newsletter  */}
        <div className="container-fluid  new-mente">
          <section id="section-podcast" className="container">
            <Row className="text-center justify-content-center align-content-center">
              <Container className="home-pollination__spacer">
                <Row xs={1} md={2} className="m-4 align-items-center justify-content-center">
                  <Col
                    xs={{ order: 1 }}
                    sm={10}
                    md={{ span: 6, order: 2 }}
                    lg={6}
                    xl={5}
                    className="p-3"
                  >
                    <div className="image-wrapper">
                      <img
                        src="/icons/home-podcast.svg"
                        alt="The Podcast image for Beela Talk, an illustraion of two women in Rosie the Riveter pose with the text Beela's Talk underneath them"
                        className="img-fluid home-shadow_img"
                      />
                    </div>
                  </Col>
                  <Col
                    xs={{ order: 2 }}
                    sm={10}
                    md={{ span: 6, order: 1 }}
                    lg={6}
                    xl={5}
                    className="p-2"
                  >
                    <h3 className="no_name_37" style={{ textAlign: "start" }}>
                      Newsletter
                    </h3>
                    <p className="m-0 B1" style={{ maxWidth: "268px", textAlign: "start" }}>
                      Let’s stay connected. Subscribe to our newsletter to stay up-to-date on
                      resources and events.
                    </p>
                    <div className="pt-3 left-center-text">
                      <Link href="https://beela.slack.com/join/shared_invite/zt-12kargaye-5R2bP0qwqNpFwPiiDAiwQQ#/shared-invite/email">
                        <a target="_blank">
                          <button type="button" className="btn button-outline">
                            Sign up
                          </button>
                        </a>
                      </Link>
                    </div>
                  </Col>
                </Row>
              </Container>
            </Row>
          </section>
        </div>
        {/* Podcast  */}
        <div className="container-fluid  new-mente">
          <section id="section-podcast" className="pod-mente">
            <Row className="text-center justify-content-center align-content-center">
              <Container className="home-pollination__spacer">
                <Row xs={1} md={2} className="m-4 align-items-center justify-content-center">
                  <Col
                    xs={{ order: 1 }}
                    sm={10}
                    md={{ span: 6, order: 2 }}
                    lg={6}
                    xl={5}
                    className="p-3"
                  >
                    <div className="image-wrapper">
                      <img
                        src="/icons/home-podcast.svg"
                        alt="The Podcast image for Beela Talk, an illustraion of two women in Rosie the Riveter pose with the text Beela's Talk underneath them"
                        className="img-fluid home-shadow_img"
                      />
                    </div>
                  </Col>
                  <Col xs={{ order: 2 }} sm={10} md={{ span: 6 }} lg={6} xl={5} className="p-2">
                    <h3 className="no_name_37" style={{ textAlign: "start" }}>
                      Podcast
                    </h3>
                    <p className="m-0 B1" style={{ maxWidth: "268px", textAlign: "start" }}>
                      Audio inspiration is a click away. Absorb unique insights around diversity,
                      equity, and inclusion in the tech industry.
                    </p>
                    <div className="pt-3 left-center-text">
                      <Link href="https://beela.slack.com/join/shared_invite/zt-12kargaye-5R2bP0qwqNpFwPiiDAiwQQ#/shared-invite/email">
                        <a target="_blank">
                          <button type="button" className="btn button-outline">
                            Listen to Beela&apos;s Talk
                          </button>
                        </a>
                      </Link>
                    </div>
                  </Col>
                </Row>
              </Container>
            </Row>
          </section>
        </div>

        <div className="container-fluid" id="support-beela-about-us">
          <div className="container">
            <div id="support-beela-section1">
              <h2 className="no_name_37">Support Beela</h2>
              <p className="B1">
                Beela is a 100% volunteer-run organization. <br />
                We’re grateful for your support in any capacity.{" "}
              </p>
            </div>
            <div id="support-beela-section2" className=" d-flex justify-content-center ">
              <div className="justify-content-center">
                <h5 className="text-center">Volunteer</h5>
                <p className="B2 about-support-p">
                  Our team is always on the lookout for new volunteers. Tell us about your skills
                  (this could be writing, social media, or design), and we’ll see if there’s a
                  match!
                </p>
              </div>
              <div className="justify-content-center">
                <h5 className="text-center">Donate</h5>
                <p className="B2 about-support-p">
                  We are a nonprofit organization, and any monetary donation helps us reach more
                  female and non-binary immigrants in Sweden.
                </p>
              </div>
            </div>
            <div className=" d-flex justify-content-center text-center py-5">
              <a href="mailto:contact@beela.se" target="_blank" rel="noreferrer">
                <button type="button" className="btn button">
                  Email Us
                </button>
              </a>
            </div>
          </div>
        </div>

        {/* Team */}
        {/* Get Voulnted*/}
        <Footer />
      </main>
    </div>
  )
}
export default StayConnected
