//Next.js component imports
import Head from "next/head"

//Component imports
import Hero from "../components/sections/stayconnected/Hero"
import JoinOurCommunity from "../components/sections/stayconnected/joinourcommunity/join"
import Newsletter from "../components/sections/stayconnected/newsletter/newsletter"
import Podcast from "../components/sections/stayconnected/podcast/podcast"
import SupportBeela from "../components/sections/about/SupportBeela"

const StayConnected = () => {
  return (
    <div>
      <Head>
        <title>Stay Connected - Beela</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <JoinOurCommunity />
      <Newsletter />
      <Podcast />
      <SupportBeela />
    </div>
  )
}
export default StayConnected
